package gov.gdgs.zs.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 事务所信息.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ZsSwsxxSwsxx implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private String id;

	/** 机构名称. */
	private String jgmc;

	/** 法定代表人. */
	private String fddbr;

	/** 省管理中心上报文号. */
	private String sglzxsbwh;

	/** 省管理中心上报时间. */
	private Date sglzxsbsj;

	/** 证书编号. */
	private String zsbh;

	/** 机构性质. */
	private String jgxz;

	/** 团体会员注册号. */
	private String tthyzch;

	/** 所在城市代码. */
	private String szcsDm;

	/** 总局批准时间. */
	private Date zjpzsj;

	/** 总局批准文号. */
	private String zjpzwh;

	/** 电话. */
	private String dh;

	/** 注册资金. */
	private Integer zczj;

	/** 总人数. */
	private Short zrs;

	/** 入会时间. */
	private Date rhsj;

	/** 税务登记号码. */
	private String swdjhm;

	/** 上级机构代码. */
	private String pid;

	/** 有效标志. */
	private Byte bzYx;

	/** 状态. */
	private Byte zt;

	/** 分所标志. */
	private Byte bzFs;

	/** 执业注税师从业人数. */
	private Short zyzsscyrs;

	/**
	 * Constructor.
	 */
	public ZsSwsxxSwsxx() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param id
	 *            ID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 机构名称.
	 * 
	 * @param jgmc
	 *            机构名称
	 */
	public void setJgmc(String jgmc) {
		this.jgmc = jgmc;
	}

	/**
	 * Get the 机构名称.
	 * 
	 * @return 机构名称
	 */
	public String getJgmc() {
		return this.jgmc;
	}

	/**
	 * Set the 法定代表人.
	 * 
	 * @param fddbr
	 *            法定代表人
	 */
	public void setFddbr(String fddbr) {
		this.fddbr = fddbr;
	}

	/**
	 * Get the 法定代表人.
	 * 
	 * @return 法定代表人
	 */
	public String getFddbr() {
		return this.fddbr;
	}

	/**
	 * Set the 省管理中心上报文号.
	 * 
	 * @param sglzxsbwh
	 *            省管理中心上报文号
	 */
	public void setSglzxsbwh(String sglzxsbwh) {
		this.sglzxsbwh = sglzxsbwh;
	}

	/**
	 * Get the 省管理中心上报文号.
	 * 
	 * @return 省管理中心上报文号
	 */
	public String getSglzxsbwh() {
		return this.sglzxsbwh;
	}

	/**
	 * Set the 省管理中心上报时间.
	 * 
	 * @param sglzxsbsj
	 *            省管理中心上报时间
	 */
	public void setSglzxsbsj(Date sglzxsbsj) {
		this.sglzxsbsj = sglzxsbsj;
	}

	/**
	 * Get the 省管理中心上报时间.
	 * 
	 * @return 省管理中心上报时间
	 */
	public Date getSglzxsbsj() {
		return this.sglzxsbsj;
	}

	/**
	 * Set the 证书编号.
	 * 
	 * @param zsbh
	 *            证书编号
	 */
	public void setZsbh(String zsbh) {
		this.zsbh = zsbh;
	}

	/**
	 * Get the 证书编号.
	 * 
	 * @return 证书编号
	 */
	public String getZsbh() {
		return this.zsbh;
	}

	/**
	 * Set the 机构性质.
	 * 
	 * @param jgxz
	 *            机构性质
	 */
	public void setJgxz(String jgxz) {
		this.jgxz = jgxz;
	}

	/**
	 * Get the 机构性质.
	 * 
	 * @return 机构性质
	 */
	public String getJgxz() {
		return this.jgxz;
	}

	/**
	 * Set the 团体会员注册号.
	 * 
	 * @param tthyzch
	 *            团体会员注册号
	 */
	public void setTthyzch(String tthyzch) {
		this.tthyzch = tthyzch;
	}

	/**
	 * Get the 团体会员注册号.
	 * 
	 * @return 团体会员注册号
	 */
	public String getTthyzch() {
		return this.tthyzch;
	}

	/**
	 * Set the 所在城市代码.
	 * 
	 * @param szcsDm
	 *            所在城市代码
	 */
	public void setSzcsDm(String szcsDm) {
		this.szcsDm = szcsDm;
	}

	/**
	 * Get the 所在城市代码.
	 * 
	 * @return 所在城市代码
	 */
	public String getSzcsDm() {
		return this.szcsDm;
	}

	/**
	 * Set the 总局批准时间.
	 * 
	 * @param zjpzsj
	 *            总局批准时间
	 */
	public void setZjpzsj(Date zjpzsj) {
		this.zjpzsj = zjpzsj;
	}

	/**
	 * Get the 总局批准时间.
	 * 
	 * @return 总局批准时间
	 */
	public Date getZjpzsj() {
		return this.zjpzsj;
	}

	/**
	 * Set the 总局批准文号.
	 * 
	 * @param zjpzwh
	 *            总局批准文号
	 */
	public void setZjpzwh(String zjpzwh) {
		this.zjpzwh = zjpzwh;
	}

	/**
	 * Get the 总局批准文号.
	 * 
	 * @return 总局批准文号
	 */
	public String getZjpzwh() {
		return this.zjpzwh;
	}

	/**
	 * Set the 电话.
	 * 
	 * @param dh
	 *            电话
	 */
	public void setDh(String dh) {
		this.dh = dh;
	}

	/**
	 * Get the 电话.
	 * 
	 * @return 电话
	 */
	public String getDh() {
		return this.dh;
	}

	/**
	 * Set the 注册资金.
	 * 
	 * @param zczj
	 *            注册资金
	 */
	public void setZczj(Integer zczj) {
		this.zczj = zczj;
	}

	/**
	 * Get the 注册资金.
	 * 
	 * @return 注册资金
	 */
	public Integer getZczj() {
		return this.zczj;
	}

	/**
	 * Set the 总人数.
	 * 
	 * @param zrs
	 *            总人数
	 */
	public void setZrs(Short zrs) {
		this.zrs = zrs;
	}

	/**
	 * Get the 总人数.
	 * 
	 * @return 总人数
	 */
	public Short getZrs() {
		return this.zrs;
	}

	/**
	 * Set the 入会时间.
	 * 
	 * @param rhsj
	 *            入会时间
	 */
	public void setRhsj(Date rhsj) {
		this.rhsj = rhsj;
	}

	/**
	 * Get the 入会时间.
	 * 
	 * @return 入会时间
	 */
	public Date getRhsj() {
		return this.rhsj;
	}

	/**
	 * Set the 税务登记号码.
	 * 
	 * @param swdjhm
	 *            税务登记号码
	 */
	public void setSwdjhm(String swdjhm) {
		this.swdjhm = swdjhm;
	}

	/**
	 * Get the 税务登记号码.
	 * 
	 * @return 税务登记号码
	 */
	public String getSwdjhm() {
		return this.swdjhm;
	}

	/**
	 * Set the 上级机构代码.
	 * 
	 * @param pid
	 *            上级机构代码
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	/**
	 * Get the 上级机构代码.
	 * 
	 * @return 上级机构代码
	 */
	public String getPid() {
		return this.pid;
	}

	/**
	 * Set the 有效标志.
	 * 
	 * @param bzYx
	 *            有效标志
	 */
	public void setBzYx(Byte bzYx) {
		this.bzYx = bzYx;
	}

	/**
	 * Get the 有效标志.
	 * 
	 * @return 有效标志
	 */
	public Byte getBzYx() {
		return this.bzYx;
	}

	/**
	 * Set the 状态.
	 * 
	 * @param zt
	 *            状态
	 */
	public void setZt(Byte zt) {
		this.zt = zt;
	}

	/**
	 * Get the 状态.
	 * 
	 * @return 状态
	 */
	public Byte getZt() {
		return this.zt;
	}

	/**
	 * Set the 分所标志.
	 * 
	 * @param bzFs
	 *            分所标志
	 */
	public void setBzFs(Byte bzFs) {
		this.bzFs = bzFs;
	}

	/**
	 * Get the 分所标志.
	 * 
	 * @return 分所标志
	 */
	public Byte getBzFs() {
		return this.bzFs;
	}

	/**
	 * Set the 执业注税师从业人数.
	 * 
	 * @param zyzsscyrs
	 *            执业注税师从业人数
	 */
	public void setZyzsscyrs(Short zyzsscyrs) {
		this.zyzsscyrs = zyzsscyrs;
	}

	/**
	 * Get the 执业注税师从业人数.
	 * 
	 * @return 执业注税师从业人数
	 */
	public Short getZyzsscyrs() {
		return this.zyzsscyrs;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ZsSwsxxSwsxx other = (ZsSwsxxSwsxx) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
